on:
  push:
    branches:
      - dev
name: build gatsby
jobs:
  build_gatsby:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12.x

      - name: yarn install
        run: yarn install

      - name: gatsby build
        env:
          GH_API_KEY: ${{ secrets.GPARKKII }}
        run: yarn build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GPARKKII_TOKEN }}
          GH_PAT: ${{ secrets.GPARKKII }}
          BUILD_DIR: 'public/'
